### ISSUE TITLE
set_selection and set_replacement not exposed

### ISSUE THREAD

**Issue by Microno95** [esa/pagmo_plugins_nonfree#13]
set_selection and set_replacement methods for the SNOPT and WORHP algorithms are not exposed in the Python interface.

**Comment by darioizzo** [comment]
This will be done by uncommenting the corresponding lines in core.cpp once the issue https://github.com/esa/pagmo2/issues/344 is closed.

**Comment by bluescarni** [comment]
I think this is now done in #18?

**Comment by darioizzo** [comment]
indeed
