### ISSUE TITLE
Worhp 1.14

### ISSUE THREAD

**Issue by darioizzo** [esa/pagmo_plugins_nonfree#5]
API changed from worhp 1.12 and pagmo plugins is no longer compatible.

**Comment by darioizzo** [comment]
We added a check on the version in #7 to avoid crashes when a mismatched library is used. To pass to worhp 1.14 is easy, but we would have to drop 1.12

I guess this is not a big problem. For the time being will keep this opened.

**Comment by darioizzo** [comment]
Also, when this ticket is close, make sure to check the seg fault problem arising when a license file is not found or is invalid.

**Comment by gabor-varga** [comment]
Hi @darioizzo , there is now WORHP 1.14 released. Is there an ETA for the upgrade to the new version? From our side, dropping support for 1.12 in favour of 1.14 is not an issue.

**Comment by darioizzo** [comment]
We do not currently have much resources / motivation to make the update. Is 1.14 providing added important features?

**Comment by darioizzo** [comment]
#21 Updated to 1.14
